# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 992a2eb84c64dba80601e75fcd02fdd4567ff06ca96cb0240570b6ebf3c5f127a63ccdab837dc4ad0ca2091ae2a6ddc505b8b04e7bb3b27b655fe66b115bd1cc

test:
  secret_key_base: 1f27dc60604fddbb9b20cdec87a7f9be9548e282dc23ddda11d4573d82ece9be96f2ea55065fb580ebf7b32c8586f27983b866bd5c62a251f15424a44418bd2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
